<a href="https://colab.research.google.com/github/Pulkit-007/Car_Price_Prediction/blob/main/Car_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [1]:
import numpy as np
import pandas as pd


Importing Dataset

In [2]:
dataset=pd.read_csv('car_data.csv')
dataset.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [3]:
dataset["selling_price"].isnull().sum()

0

In [4]:
dataset["owner"].isnull().sum()

0

In [5]:
dataset["owner"].value_counts()

First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

In [6]:
dataset["seller_type"].value_counts()

Individual          3244
Dealer               994
Trustmark Dealer     102
Name: seller_type, dtype: int64

Encoding the Data

In [7]:
x=dataset.iloc[:,[1,3,4,6]].values  #independent variables
y=dataset.iloc[:,2].values 

In [8]:
x

array([[2007, 70000, 'Petrol', 'Manual'],
       [2007, 50000, 'Petrol', 'Manual'],
       [2012, 100000, 'Diesel', 'Manual'],
       ...,
       [2009, 83000, 'Petrol', 'Manual'],
       [2016, 90000, 'Diesel', 'Manual'],
       [2016, 40000, 'Petrol', 'Manual']], dtype=object)

In [9]:
y

array([ 60000, 135000, 600000, ..., 110000, 865000, 225000])

In [10]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
x[:,2]=lb.fit_transform(x[:,2])
lb1=LabelEncoder()
x[:,3]=lb1.fit_transform(x[:,3]) 

In [11]:
x[:,2]

array([4, 4, 1, ..., 4, 1, 4], dtype=object)

In [12]:
x[:,3]

array([1, 1, 1, ..., 1, 1, 1], dtype=object)

Splitting the data into Train and Test Set

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(x,y,test_size=0.02,random_state=0)
print(X_train[:,:])

[[2014 80000 1 1]
 [2015 70000 1 1]
 [2015 32686 4 1]
 ...
 [2016 22000 4 1]
 [2015 70000 1 1]
 [2013 62000 4 1]]


**Training the Model**

In [20]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=300,random_state=0)
regressor.fit(X_train,Y_train)

RandomForestRegressor(n_estimators=300, random_state=0)

In [21]:
accuracy=regressor.score(X_test,Y_test)
print(accuracy*100,"%")

91.0813509435734 %


**Performing the test on given input**

In [25]:
new_data=[2017,7000,"Petrol","Manual"]
new_data[2]=lb.fit_transform([new_data[2]])[0]
new_data[3]=lb1.fit_transform([new_data[3]])[0]

In [27]:
new_data
regressor.predict([new_data])

array([6172242.46031746])

Saving the model and encoder using pickle

In [28]:
import pickle
pickle.dump(regressor,open('regressor.pkl','wb'))
pickle.dump(lb,open('lb','wb'))
pickle.dump(lb1,open('lb1','wb'))